### ISSUE TITLE
Produce outputs

### ISSUE THREAD

**Issue by tieguy** [sustainers/discussions#2]
I've thrown my notes from the legal issues final group into a [gist](https://gist.github.com/tieguy/02764b57e430739c999e6f0b5eb40c6e). Is there a best place to put them here, or at least link out to them?

(I'd assume wiki, but it looks disabled in the project; not sure if that's just oversight or if there is a long-term plan.)

Thanks!

**Comment by jdorfman** [comment]
@tieguy great question and thanks for starting the convo here. We are talking about this in this issue https://github.com/sustainers/website/issues/132 which in hindsight should have been posted in [discussions](https://github.com/sustainers/discussions/) (old habits die hard). 

I'll link to this thread and try to move the conversation over. In the meantime feel free to join that thread. Also great idea about the wiki.

**Comment by chadwhitacre** [comment]
Let's use this to carry forward the production of outputs from the initial Sustain event. Folding https://github.com/sustainers/website/issues/132 into here.

**Comment by chadwhitacre** [comment]
Basic plan per https://github.com/sustainers/website/issues/132#issuecomment-311134321:

1. send out message "We're typing up notes, get in touch if you want to help with that. Also, opt-out on participant list."
1. retake pictures of notes pages as needed
1. organize photos with filenames per the agenda
1. hire someone to transcribe, prioritizing:
    1. "Where from here?"
    1. lists
    1. etc.
1. organize a folder and share the transcripts and photos with the community
    - invite review for consent and redaction
1. write up agenda as it happened

Once notes are typed up revisit the idea of writing up a summary report/blog post. Share redacted transcripts/photos publicly.

**Comment by jdorfman** [comment]
I put the draft email in a Google Doc while we edit. I applied @alnermcgunn's suggestions. @piamancini will add her changes.

**Comment by jdorfman** [comment]
Email sent yesterday. Metrics thus far:

![image](https://user-images.githubusercontent.com/398230/27649037-655f767c-5be5-11e7-957e-16c7897e5445.png)

**Comment by piamancini** [comment]
emails with activity boards have been sent to everyone in charge already.

**Comment by chadwhitacre** [comment]
Perhaps we could publish something on opensource.com, to bookend @jdorfman's original post:

https://opensource.com/article/17/4/become-open-source-sustainer
