### ISSUE TITLE
SustainUK 2018

### ISSUE THREAD

**Issue by jdorfman** [sustainers/discussions#6]
The 2nd Sustain event will be in London on Oct 25th, 2018 so mark your calendars. Till then join us on Slack (https://changelog.slack.com/ `#sustain`), follow us on [Twitter](https://twitter.com/sustainoss).

If you want to reach the organizers via email: `uk2018 at sustainoss .org`

More TBA! 🎉

**Comment by andrew** [comment]
Perfectly lines up with Mozfest in London too!

**Comment by jdorfman** [comment]
The SustainUK 2018 site is now live https://sustainoss.org/

Please let us know if you find any issues or if would like to contribute: https://github.com/sustainers/website/issues

Thanks!
